import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UIProvider } from "@yamada-ui/react";
import OsuTokenProvider from "@/components/stores/OsuTokenProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Osu! FC Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let token: string = "";
  // TODO: tokenをfetchする処理
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProvider>
          <OsuTokenProvider token={token}>{children}</OsuTokenProvider>
        </UIProvider>
      </body>
    </html>
  );
}
